# Matrices in pytorch


-Professor: M.Sc.Saul Calderon.

- Authors: 
    - M. Sc. Saúl Calderón, Dr. Juan Esquivel. 

# Importing dependencies

In [0]:
# Since Collab is being used, it is necessary to install Pytorch
!pip install torch
import torch as torch

import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm


# Matrices for rewriting equations and functions

The following equation system:
$$\begin{array}{c}
4x_{1}-5x_{2}=-13\\
-2x_{1}+3x_{2}=9
\end{array}$$
can be rewritten interms of vectors and matrices as follows:
$$A\,\vec{x}=\overrightarrow{b}\Rightarrow\vec{x}=A^{-1}\overrightarrow{b}$$


In [0]:

def testSolveEquationSystem1():
    """
    Solve an equation system with one solution
    """
    A = torch.tensor([[4.0, -5.0], [-2.0, 3.0]])
    #create a 2d tensor even for vectors, to avoid to create 1dtensor type creation
    b = torch.tensor([[-13.0], [9.0]])
    Ainv = A.inverse()
    x = Ainv.mm(b)
    print(x)
    

def testSolveEquationSystem2():
    """
    Solve an equation system with multiple solutions (one row is linear combination of the other)
    """
    A = torch.tensor([[4.0, -5.0], [8.0, -10.0]])
    #create a 2d tensor even for vectors, to avoid to create 1dtensor type creation
    b = torch.tensor([[-13.0], [9.0]])
    Ainv = A.inverse()
    x = Ainv.mm(b)
    print(x)
    
    
testSolveEquationSystem1()
    

tensor([[3.],
        [5.]])


## Identity matrix

In [0]:
# Create an identity matrix
Identity = torch.eye(5)
print(Identity)



tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


## Matrix Transpose
The transpose operation is only defined for 2D tensors

In [0]:
#Transpose cannot work with 1D tensors
w = torch.tensor([1, 2, 3])
#check tensor type
print("Type 1D tensor: ", w.type(), w.shape)

#row vector in 2D tensor
w2Drow = w.reshape(-1, w.shape[0])
print("Type 2D Tensor ", w2Drow.type(), w2Drow.shape)

print("row vector ", w2Drow)

#transpose receives the first dim0 to switch, and the second dim1 to swap, usually 0,1 is the order
wDrowT = w2Drow.transpose(0, 1)

print(wDrowT)


Type 1D tensor:  torch.LongTensor torch.Size([3])
Type 2D Tensor  torch.LongTensor torch.Size([1, 3])
row vector  tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])


## Matrix indexing and concatenation
Tensors can be indexed using the slicing operators, and concatenated using the function cat

In [0]:
# Dot product of matrices doesnt exist for 2D Tensors
A = torch.tensor([[1, 2, 3],[1, 2, 3]])
B = torch.tensor([[5, 5],[6, 6],[7, 7]])
#WE RECOMMEND ALWAYS USE 2D TENSORS, EVEN IF IT IS A VECTOR
#dotProduct = A.dot(B) it doesnt work, it is defined for 1D tensors only. 
#SOME OPERATORS ARE DEFINED FOR 1D TENSORS ONLY, AND SOME OF THEM ARE DEFINED FOR 2D TENSORS

#Create a matrix C, concatenating the matrix A along its rows
C = torch.cat((A, A), 0)
#Create a matrix D, concatenating the matrix A along its columns
D = torch.cat((B, B), 1)
print("C concatenado, ", C)
print("B concatenado ", B)


#Put ceros in column 1 and 2, from row 0
C[0, 1:3] = 0;



#Put ones in column 1 and all the rows
D[:, 1] = 1
print(D)


C concatenado,  tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
B concatenado  tensor([[5, 5],
        [6, 6],
        [7, 7]])
tensor([[5, 1, 5, 5],
        [6, 1, 6, 6],
        [7, 1, 7, 7]])


## Matrix flatenning
Matrix flatenning refers to create a column or row vector with all the elements within a matrix.
See more at http://deeplizard.com/learn/video/fCVuiW9AFzY

In [0]:
A = torch.tensor([[1, 2, 3],[6, 24, 32]])
print("A original ", A)

Af= A.reshape(A.shape[0] * A.shape[1], -1)
print("A reshaped ", Af)

#if we want to remove one dimension of the tensor, we can use squeeze, transforming from 2D to 1D tensor
Afs = Af.squeeze()
print(""Afs)



A original  tensor([[ 1,  2,  3],
        [ 6, 24, 32]])
A reshaped  tensor([[ 1],
        [ 2],
        [ 3],
        [ 6],
        [24],
        [32]])
tensor([ 1,  2,  3,  6, 24, 32])


## Matrix multiplication

Product of two matrices $A\in\mathbb{R}^{m\times n}$ and $B\in\mathbb{R}^{n\times p}$ is given by:
$$
C=A\,B=\begin{bmatrix}- & \vec{a}_{1,:}^{T} & -\\
- & \vec{a}_{2,:}^{T} & -\\
 & \vdots\\
- & \vec{a}_{m,:}^{T} & -
\end{bmatrix}\,\begin{bmatrix}| & | & \ldots & |\\
\vec{b}_{1,:} & \vec{b}_{2,:} & \ldots & \vec{b}_{p,:}\\
| & | & \ldots & |
\end{bmatrix}=\begin{bmatrix}\vec{a}_{1,:}^{T}\vec{b}_{1,:} & \vec{a}_{1,:}^{T}\vec{b}_{2,:} & \cdots & \vec{a}_{1,:}^{T}\vec{b}_{p,:}\\
\vec{a}_{2,:}^{T}\vec{b}_{1,:} & \vec{a}_{2,:}^{T}\vec{b}_{2,:} & \cdots & \vec{a}_{2,:}^{T}\vec{b}_{p,:}\\
\vdots & \vdots & \ddots & \vdots\\
\vec{a}_{m,:}^{T}\vec{b}_{1,:} & \vec{a'}_{m}^{T}\vec{b}_{2,:} & \cdots & \vec{a}_{m,:}^{T}\vec{b}_{p,:}
\end{bmatrix}
$$


In [0]:
#extract one row
print("matriz A")
print(A)
print("matriz B")
print(B)

a = A[0, :]
# extract one column
b = B[:, 0]
#calculate dot product
c = torch.dot(a,b)
print("Dot product")
print(c)


print("C = A B")
C = A.mm(B)
print(C)

matriz A
tensor([[ 1,  2,  3],
        [ 6, 24, 32]])
matriz B
tensor([[5, 5],
        [6, 6],
        [7, 7]])
Dot product
tensor(38)
C = A B
tensor([[ 38,  38],
        [398, 398]])


## Element wise multiplication of matrices

The element wise multiplication of matrices A and B result in a matrix C with same dimensions, and multiplies its entries.


In [0]:
A = torch.tensor([[1, 2], [3, 0]])
B = torch.tensor([[5, 6], [7, 0]])
C = A * B
print(C)
#Element wise multiplication allows us to calculate dot product of matrices
dotProduct = C.sum()

print("Dot product: ", dotProduct)

tensor([[ 5, 12],
        [21,  0]])
Dot product:  tensor(38)


## External product of vectors
For two vectors

$\overrightarrow{x}\in\mathbb{R}^{m\times1}$, $\overrightarrow{y}\in\mathbb{R}^{1\times n} $ is given by: 
$$
\vec{x}\:\vec{y}^{T}\in\mathbb{R}^{m\times n}=\begin{bmatrix}x_{1}\\
x_{2}\\
\vdots\\
x_{m}
\end{bmatrix}\begin{bmatrix}y_{1} & y_{2} & \cdots & y_{n}\end{bmatrix}=\begin{bmatrix}x_{1}y_{1} & x_{1}y_{2} & \cdots & x_{1}y_{n}\\
x_{2}y_{1} & x_{2}y_{2} & \cdots & x_{2}y_{n}\\
\vdots & \vdots & \ddots & \vdots\\
x_{m}y_{1} & x_{m}y_{2} & \cdots & x_{m}y_{n}
\end{bmatrix}$$

In [0]:
#1x3 vector
a = torch.tensor([[1, 2, 3]])
#3x1 vector
b = torch.tensor([[5], [6], [7]])
#3x3 matrix
externalProduct = b.mm(a)

print(externalProduct)

#what happens if a elements are equal to b?
b = torch.tensor([[1], [2], [3]])
externalProduct2 = b.mm(a)

print("External product of the same vector", externalProduct2)



tensor([[ 5, 10, 15],
        [ 6, 12, 18],
        [ 7, 14, 21]])
External product of the same vector tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])


# Matrix-vector product
$$
\overrightarrow{y}=A\,\overrightarrow{x}=\begin{bmatrix}| & | & \ldots & |\\
\vec{a}_{:,1} & \vec{a}_{:,2} & \ldots & \vec{a}_{:,n}\\
| & | & \ldots & |
\end{bmatrix}\,\begin{bmatrix}x_{1}\\
x_{2}\\
\vdots\\
x_{n}
\end{bmatrix}=\left[\vec{a}_{:,1}\right]x_{1}+\left[\vec{a}_{:,2}\right]x_{2}+\ldots+\left[\vec{a}_{:,n}\right]x_{n}.
$$

In [0]:
A = torch.tensor([[2, 3], [4, 5]])
x = torch.tensor([[2], [3]])
#linear combination of A's columns
#y = 2 [[2], [4]] + 3 [[3], [5]] = [[13], [23]]
y = A.mm(x)
print(y)

tensor([[13],
        [23]])


## Symmetric Matrices
A squared matrix is symmetric if  $A=A^{T}$

In [0]:
def isSymmetric(A):
    """
    A: input matrix
    """
    At = A.transpose(0, 1)
    return (torch.all(A.eq(At)))
        
#check wether the external product of the same vector is symmetric
B = torch.tensor([[1, 5, 3], [2, 7, 9], [2, 1, 4]])
Bt = B.transpose(0, 1)

Sym1 = B.mm(Bt)
print("Sym1 ")
print(Sym1)
print(isSymmetric(Sym1))

C = torch.tensor([[3, 4, 4], [5, 6, 7], [4, 5, 6]])
Ct = C.transpose(0, 1)
Sym2 = C + Ct
print("Sym2")
print(Sym2)
print(isSymmetric(Sym2))



isSymmetric(externalProduct2)   
    

Sym1 
tensor([[ 35,  64,  19],
        [ 64, 134,  47],
        [ 19,  47,  21]])
tensor(1, dtype=torch.uint8)
Sym2
tensor([[ 6,  9,  8],
        [ 9, 12, 12],
        [ 8, 12, 12]])
tensor(1, dtype=torch.uint8)


tensor(1, dtype=torch.uint8)

For any squared non symmetric matrix $A\mathbb{\in R}^{n\times n}$, we can build a symmetric matrix $A+A^{T}$ 


In [0]:
AnonSym = torch.tensor([[3, 7, 5], [7, 3, 4], [3, 2, 1]])
print(AnonSym)
Bsym = AnonSym + AnonSym.transpose(0, 1)
print(Bsym)
#check if it is symmetric
isSymmetric()

tensor([[3, 7, 5],
        [7, 3, 4],
        [3, 2, 1]])
tensor([[ 6, 14,  8],
        [14,  6,  6],
        [ 8,  6,  2]])


## Matrix Rank
Lineally dependent vectors  $\left\{ \vec{x}_{1},\vec{x}_{2},\ldots,\vec{x}_{n}\right\} \subset\mathbb{R}^{m}$
if at least one vector can be written as a lineal combination of any of the rest: 
$$
\vec{x}_{j}=\sum_{i=1}^{n-1}\alpha_{i}\vec{x}_{i}
$$

In [0]:
#Rank of 10x10 identity matrix
Identity = torch.eye(10)
MatrixRank = np.linalg.matrix_rank(Identity.numpy())
print("Rango de matriz identidad")
print(MatrixRank)
#squared matrix with linear combination of rows, rank inferior than number of rows and columns
A = torch.tensor([[4.0, -5.0], [8.0, -10.0]])
MatrixRank = np.linalg.matrix_rank(A.numpy())
print("Matrix A rank ", MatrixRank)
#squared matrix with independent rows
B = torch.tensor([[4.0, -5.0], [-2.0, 3.0]])
MatrixRank = np.linalg.matrix_rank(B.numpy())
print("Matrix B rank ", MatrixRank)



Rango de matriz identidad
10
Matrix A rank  1
Matrix B rank  2


## Inverse Matrix
The inverse matrix satisfies $A^{-1}A=I=A\,A^{-1}$ and also
$\left(A\,B\right)^{-1}=B^{-1}A^{-1}.$

In [0]:

def checkInverseMatrixMultiplicationProperty(A, B):
    """
    Checks matrix inverse multiplication property
    A: squared, full rank, non singular, invertible matrix
    B: squared, full rank, non singular, invertible matrix
    """
    Ainv = A.inverse()
    Binv = B.inverse()
    C = A.mm(B)
    CinvLeft = C.inverse()
    
    
    multRight = Binv.mm(Ainv)
    
    #for floating matrices, sum of difference must be small 
    return (CinvLeft - multRight).sum() < 0.1e-5


C = torch.tensor([[3.0, 5.0], [1.0, 7.0]])
#lets verify the rank
rankC = np.linalg.matrix_rank(C.numpy())
print("Rango de C ", rankC)


print ("Property check: ", checkInverseMatrixMultiplicationProperty(B,C))
    

    
    
    
    

Rango de C  2
Property check:  tensor(1, dtype=torch.uint8)


## Pseudo inverse matrix
The following is a very important property:
1. $$ \left(A^{T}A\right)^{-1}A^{T}\approx A^{+} $$

2. 
$$\left(A^{T}A\right)^{+}A^{T}=A^{+}$$

In [0]:
def checkPseudoInverseProperty1(A):
    """
    Check pseudo inverse property 1
    """
    Apinv = torch.tensor(np.linalg.pinv(A.numpy()))
    At = A.transpose(0, 1)
    left = At.mm(A).inverse().mm(At)
    
    
    return (left - Apinv).sum() < 0.1e-5
  
def checkPseudoInverseProperty2(A):
    """
    Check pseudo inverse property 2
    Pytorch pinv implementation is not recommended for non invertible matrices
    """
    
    #Apinv = A.pinverse()
    Apinv = torch.tensor(np.linalg.pinv(A.numpy()))
    print(Apinv)
    
    At = A.transpose(0, 1)
    left = torch.tensor(np.linalg.pinv(At.mm(A).numpy())).mm(At)
  
    
    return (left - Apinv).sum() < 0.1e-5
    
    
#pseudo inverse of invertible matrix  
print("C matrix")
print(C)


Cinv = C.inverse()
Cpinv = C.pinverse()
print("Inverted C ", Cinv)
print("Pseudo inverted C", Cpinv)

I = C.mm(Cpinv)
print("C * Cpinv ", I)
#check pseudo inverse property for invertible matrix
checkPseudoInverseProperty1(C)

#pseudo inverse of non invertible square matrix
D = torch.tensor([[3.0, 5.0], [6.0, 10.0]])
Dpinv = torch.tensor(np.linalg.pinv(D.numpy()))

print("Dpinv")
print(Dpinv)
print("Check second property ")
print(checkPseudoInverseProperty2(D))


D.inverse()




#the inverse property is not satisfied
I = D.mm(Dpinv)
print("Dinv * D ", I)
print("PINV ", Dpinv)
#check pseudo inverse property
#print("Satisfies pseudo inverse property 1: ", checkPseudoInverseProperty1(D))
result = checkPseudoInverseProperty1(D)
print("Satisfies pseudo inverse property 2: ", result)




C matrix
tensor([[3., 5.],
        [1., 7.]])
Inverted C  tensor([[ 0.4375, -0.3125],
        [-0.0625,  0.1875]])
Pseudo inverted C tensor([[ 0.4375, -0.3125],
        [-0.0625,  0.1875]])
C * Cpinv  tensor([[1.0000e+00, 1.7881e-07],
        [5.9605e-08, 1.0000e+00]])
Dpinv
tensor([[0.0176, 0.0353],
        [0.0294, 0.0588]])
Check second property 
tensor([[0.0176, 0.0353],
        [0.0294, 0.0588]])
tensor(1, dtype=torch.uint8)


RuntimeError: ignored

## Vector projection
Projection of $\vec{y}\in\mathbb{R}^{n}$ over the vectors generated by the set of base vectors $\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \qquad\vec{a}_{i}\in\mathbb{R}^{n}$
$$
\textrm{proy}\left(\vec{y};\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \right)=\textrm{argmin}_{\vec{v}\in\textrm{espacioGenerado}\left(\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \right)}\left\Vert \vec{v}-\vec{y}\right\Vert _{2}.
$$
with the generated space given by the column space:
$$
\mathcal{C}\left(A\right)=\left\{ \vec{v}\in\mathbb{R}^{n}:\vec{v}=A\,\vec{x},\;\vec{x}\in\mathbb{R}^{m},\:A\in\mathbb{R}^{n\times m}\right\} 
$$

with the optimal solution given by:

$$
\textrm{proy}\left(\vec{y};A\right)=A\,\left(A^{T}A\right)^{-1}A^{T}\vec{y}
$$


### Example 1: Same number of base vectors $m$ and vector dimensionality $n$, lineally independent base vectors
Given the independent base vectors  $$\vec{a}_{1}=\begin{bmatrix}0.5\\
0\\
0
\end{bmatrix}, \vec{a}_{2}=\begin{bmatrix}0\\
0.25\\
0
\end{bmatrix},  \vec{a}_{3}=\begin{bmatrix}0\\
0\\
2
\end{bmatrix}$$
Calculate the projection vector  $\textrm{proy}\left(\vec{y};A\right)\in\mathbb{R}^{3}$ with $ \vec{y}=\begin{bmatrix}1\\
2\\
3
\end{bmatrix}$ and evaluate its error

### Example 2: Same number of base vectors $m$ and vector dimensionality $n$, lineally dependent base vectors
$$
\vec{a}_{1}=\begin{bmatrix}0.5\\
0\\
0
\end{bmatrix}, \vec{a}_{2}=\begin{bmatrix}1\\
0\\
0
\end{bmatrix}  \vec{a}_{3}=\begin{bmatrix}0\\
1\\
2
\end{bmatrix}
$$
Calculate the projection vector  $\textrm{proy}\left(\vec{y};A\right)\in\mathbb{R}^{3}$ with $ \vec{y}=\begin{bmatrix}1\\
2\\
3
\end{bmatrix}$ and evaluate its error

### Example 3: More base vectors $m$ than vector dimensionality $n$
With the following base vectors $$\vec{a}_{1}=\begin{bmatrix}0.5\\
0\\
0
\end{bmatrix}, \vec{a}_{2}=\begin{bmatrix}0\\
0.25\\
3
\end{bmatrix}, \vec{a}_{3}=\begin{bmatrix}0\\
0\\
2
\end{bmatrix}, \vec{a}_{3}=\begin{bmatrix}23\\
5\\
3
\end{bmatrix}$$

### Example 4: Less base vectors $m$ than vector dimensionality $n$
Given the following base vectors:

$$ \vec{a}_{1}=\begin{bmatrix}5\\
7\\
21
\end{bmatrix},  \vec{a}_{2}=\begin{bmatrix}0\\
13\\
9
\end{bmatrix}$$